### ISSUE TITLE
Примитивы вместо объектов

### ISSUE THREAD

**Issue by XakepSDK** [VKCOM/vk-java-sdk#10]
Используйте примитивы вместо объектов! Long -> long, Integer -> int, Boolean -> boolean и т. д.!
Примитивы быстрее объектов в очень много раз!

**Comment by 7Dump** [comment]
@XakepSDK но нельзя проверить на null

**Comment by tsivarev** [comment]
@XakepSDK Да, иногда нужно уметь проверять поля на null.
