### ISSUE TITLE
Не получить список друзей

### ISSUE THREAD

**Issue by nuancat** [VKCOM/vk-java-sdk#11]
Собираю запрос для получения друзей с полем "пол". 

Запрос
`List<UserXtrLists>friends = vk.friends().get(actor).unsafeParam("fields", "sex").execute();`

Пишет, что 
`incompatible types: GetResponse cannot be converted to List<UserXtrLists>`

В какой объект можно скинуть массив друзей?

**Comment by tsivarev** [comment]
Это можно сделать так:

```
GetFieldsResponse response = VK.friends().get(ACTOR, UserField.SEX).execute();
List<UserXtrLists> friends = response.getItems();
```
