### ISSUE TITLE
Support API 5.80

### ISSUE THREAD

**Issue by vashchenkov** [VKCOM/vk-java-sdk#120]
Does sdk library will support API version 5.80?

**Comment by sboychenko** [comment]
Присоединяюсь к вопросу. Интересно опробовать возможности новых фич. Особенно клавиатуры для ботов

**Comment by GolovlevaM** [comment]
Поддерживаю вопрос, т.к. многие методы работы с сообщениями уже depricated.

**Comment by alatushkin** [comment]
Видимо, нет (

**Comment by alatushkin** [comment]
@vashchenkov @sboychenko @GolovlevaM 

Немного пострадал и решил пойти другим путем https://github.com/alatushkin/kotlin-vk-api

**Comment by aotd1** [comment]
Лучше поздно чем совсем забросить, API 5.126 в v1.0.8
