### ISSUE TITLE
Error execute

### ISSUE THREAD

**Issue by JLoskin** [VKCOM/vk-java-sdk#13]
**What have:**
ERROR com.vk.api.sdk.client.ApiRequest - Invalid JSON: {"response":31}
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

**What do:**
JsonElement response = vk.execute().storageFunction(actor, "getMessageCount")
                        .unsafeParam("user_id", idPersonField.getText())
                        .execute();

_return API.messages.getHistory({"count": 0, "user_id": Args.user_id}).count;_

**Comment by JLoskin** [comment]
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonArray

**Comment by tsivarev** [comment]
Thanks! It will be fixed in 0.3.3 version.
