### ISSUE TITLE
VK Streaming API - Pong wait timeout

### ISSUE THREAD

**Issue by Kabal163** [VKCOM/vk-java-sdk#139]
Добрый день. После открытия стрима падает по таймауту:
`StreamingCallbackMessage{code=300, serviceMessage=StreamingServiceMessage{message='Pong wait timeout', serviceCode=3001}, event=null}`

Мой код:
`public static void main(String[] args)
            throws ClientException,
            ApiException,
            ExecutionException,
            InterruptedException {

        TransportClient transportClient = HttpTransportClient.getInstance();
        VkApiClient vk = new VkApiClient(transportClient);
        VkStreamingApiClient streamingClient = new VkStreamingApiClient(transportClient);

        ServiceClientCredentialsFlowResponse authResponse = vk.oAuth()
                .serviceClientCredentialsFlow(APP_ID, CLIENT_SECRET)
                .execute();

        ServiceActor serviceActor = new ServiceActor(APP_ID, authResponse.getAccessToken());

        GetServerUrlResponse getServerUrlResponse = vk.streaming().getServerUrl(serviceActor).execute();
        StreamingActor streamingActor = new StreamingActor(getServerUrlResponse.getEndpoint(), getServerUrlResponse.getKey());
        
        streamingClient.stream().get(streamingActor, new StreamingEventHandler() {
            @Override
            public void handle(StreamingCallbackMessage message) {
                System.out.println(message);
            }
        }).execute();
    }`

Рулы настроены. Успеваю получить 3-4 сообщения и после этого закрывается коннекшен.

**Comment by Kabal163** [comment]
Если реализовать метод **onPingFrame()** в классе **WSPingListener** - все работает.
https://ru.stackoverflow.com/questions/978953/vk-streaming-api-pong-wait-timeout

**Comment by Mobyman** [comment]
Спасибо, исправлено!
