### ISSUE TITLE
Wrong version in Client's USER_AGENT

### ISSUE THREAD

**Issue by JarvisCraft** [VKCOM/vk-java-sdk#140]
https://github.com/VKCOM/vk-java-sdk/blob/0adc57e0123ad36cfaa71a2c704fede92f59dd47/sdk/src/main/java/com/vk/api/sdk/httpclient/HttpTransportClient.java#L46 wrong version of the SDK is specified in `String` constant.

**Comment by Mobyman** [comment]
Спасибо, исправлено!
