### ISSUE TITLE
Не правильно парсится Photo при входящем событии.

### ISSUE THREAD

**Issue by ura3462246** [VKCOM/vk-java-sdk#150]
В классе Photo
https://github.com/VKCOM/vk-java-sdk/blob/v1.0.2/sdk/src/main/java/com/vk/api/sdk/objects/photos/Photo.java
https://vk.com/dev/objects/photo
 есть коллекция "images". И после парсинга в CallbackApi поле images не заполняется хотя данные приходят. И вообще я не нашел такого поля в доке ВК https://vk.com/dev/objects/photo . Тут только поле sizes, которое и приходит в json, но не парсится.
Возможно я ошибся в чем-то другом, помогите, пожалуйста.

Использую версию 1.0.2
API VK пробовал версии 5.73(как указано в документации) и последнюю 5.95.

**Comment by Zip222** [comment]
Что fixed-то? Оно как возвращалось null'овым, так и возвращается.

**Comment by aotd1** [comment]
Fixed in v1.0.7, please recheck
