### ISSUE TITLE
VK Streaming API - Pong wait timeout

### ISSUE THREAD

**Issue by VladimirBogomolov** [VKCOM/vk-java-sdk#155]
Версия sdk 1.0.2
После открытия стрима падает по таймауту:
`StreamingCallbackMessage{code=300, serviceMessage=StreamingServiceMessage{message='Pong wait timeout', serviceCode=3001}, event=null}`

Был issue https://github.com/VKCOM/vk-java-sdk/issues/139,  в котором эта проблема была исправлена. В версии 1.0.2 это проблема проявлятся вновь видимо при мердже был удален метод 
`public void onPing(byte[] message)` в `WSPingListener`
предлагаю восстановить

**Comment by aotd1** [comment]
Please recheck it in the fresh release v1.0.8
