### ISSUE TITLE
Remove log4j from compile dependencies

### ISSUE THREAD

**Issue by ortex** [VKCOM/vk-java-sdk#159]
Please, remove log4j from compile dependencies.

User must be able to decide what logger use e.g. logback or log4j.

Also, before https://github.com/VKCOM/vk-java-sdk/commit/14486dc8c0121d1ea64488f38e3cb13f1894df2f#diff-8a4c24aad914d8f05e1d455dd29218b8 it was OK.
@Mobyman please, have a look.

P.S: you have duplicate 'commons-collections4' lib in dependencies. https://github.com/VKCOM/vk-java-sdk/blob/master/sdk/build.gradle#L10-L12

**Comment by aotd1** [comment]
Fixed in 1.0.8
