### ISSUE TITLE
Invalid method name in CallbackApi example in README

### ISSUE THREAD

**Issue by AppLoidx** [VKCOM/vk-java-sdk#169]
В объекте **Message** нету метода `getBody()`, который использовался в примере на README:
```java
public class CallbackApiHandler extends CallbackApi {
  @Override
  public void messageNew(Integer groupId, Message message) {
    System.out.println(message.getBody());
  }
}
```

Следует заменить `message.getBody()` на `message.getText()`

**Comment by AppLoidx** [comment]
Вот Pull Request: 
https://github.com/VKCOM/vk-java-sdk/pull/167/commits/26d341670e0149b2f245b222c5a8bff711a6f5cd

**Comment by aotd1** [comment]
Thanks, fixed in 1.0.8
