### ISSUE TITLE
Интерфейс groups.getCallbackConfirmationCode возвращает неверный код

### ISSUE THREAD

**Issue by liemei** [VKCOM/vk-java-sdk#186]
Я использую код, возвращенный интерфейсом groups.getCallbackConfirmationCode в программе, и страница API обратного вызова фонового соединения vk не совместима. Я использую код, возвращаемый программой, чтобы убедиться, что код неправильный. Я попробовал java SDK и .net SDK Содержимое кода, возвращаемое этими двумя SDK, одинаково, но отличается от фоновой страницы. Как решить эту проблему? Мне нужна помощь  
Мой groupid - 186648891, код подтверждения на фоновой странице - 62dfc19d, но интерфейс groups.getCallbackConfirmationCode возвращает cbbd0d4d.

**Comment by GurevichAleksey** [comment]
https://vk.com/dev/groups.getCallbackConfirmationCode, секция "Результат"

> Обратите внимание, что код, возвращаемый методом, можно использовать только для настройки сервера средствами API. В настройках Вашего сообщества на сайте ВКонтакте код будет отличаться.

**Comment by CaCTuCaTu4ECKuu** [comment]
Та же проблема. Вопрос все равно актуален - какая в этом вообще логика.
Я использую ключ доступа аккаунта, я использую ключ доступа группы - код мне возвращает, разный, но все равно не тот, что нужен.
Смысл в том чтобы автоматически подключить сообщество к боту, но в итоге все равно нужно код прописывать руками.
Лично я не первый раз сталкиваюсь и регулярно люди, которым нужна эта функция, пишут нам в VkNet.
Если люди пишут о проблеме, так может нужно что-то поменять. Вообще не в кайф объяснять каждый раз что это ВК так сделал?

**Comment by CaCTuCaTu4ECKuu** [comment]
Что примечательно - vk.com/dev/groups.getCallbackConfirmationCode
Возвращает код правильно. Человек не знающий напишет код будучи уверенным что все будет работать как надо

**Comment by PerfilovStanislav** [comment]
1. Запрашиваете код через getCallbackConfirmationCode.
2. Сохраняете его где-нибудь, например в редисе.
3. Выполняете addCallbackServer
4. От VK прилетает запрос в виде `{"type": "confirmation", "group_id": 123, "secret": "abc321"}`
5. Достаёте из хранилища ваш код (шаг 2)
6. отдаёте его
Профит =)

**Comment by CaCTuCaTu4ECKuu** [comment]
@PerfilovStanislav спасибо, жду статью на хабре

Кстати последнее обновление, проблема, кажется, решилась, месяц назад человек настраивал автоответчик и писал по другой ошибке, но при попытке воспроизвести также выяснилось что сработала автоматика и код пришёл верный, но я подробно не проверял - заработало и хорошо.

**Comment by aotd1** [comment]
Код подтверждения в интерфейсе vkcom отличается от того что отдаёт API метод groups.getCallbackConfirmationCode.
Это нормально, т.к. код в интерфейсе предназначен для подтверждения через интерфейс. 
Код полученный из API - для создания Callback сервера через API (addCallbackServer).

Это не слишком очевидное поведение, возможно различие стоит устранить, но пока это работает так.

**Comment by CaCTuCaTu4ECKuu** [comment]
Это поведение однозначно нужно устранить, но в любом случае это должно быть где-то описано
Возможно это уже и исправили, сейчас вроде работает
