### ISSUE TITLE
Ошибка "Can't parse json response" при выполнении groups.getMembers с доп. полями

### ISSUE THREAD

**Issue by devgor88** [VKCOM/vk-java-sdk#189]
При запросе `vk.groups().getMembers(defActor).groupId(id).fields(Fields.SEX).offset(1000).execute())` вылетает исключение

> 17:21:29.595 [main] ERROR com.vk.api.sdk.client.ApiRequest - Invalid JSON: {<тут весь ответ>}
> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.items[0]
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:927) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:994) ~[gson-2.8.5.jar:?]
> 	at com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:101) [sdk-1.0.6.jar:?]
> 	at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:64) [sdk-1.0.6.jar:?]
> 	at ru.devgor.Main.info(Main.java:107) [whois/:?]
> 	at ru.devgor.Main.main(Main.java:74) [whois/:?]
> Caused by: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.items[0]
> 	at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:241) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.5.jar:?]
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.5.jar:?]
> 	... 6 more
> Exception in thread "main" com.vk.api.sdk.exceptions.ClientException: Can't parse json response
> 	at com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104)
> 	at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:64)
> 	at ru.devgor.Main.info(Main.java:107)
> 	at ru.devgor.Main.main(Main.java:74)

Все происходит из-за того, что gson не ожидает подробной информации о людях, он ждет лишь их id.

Временное решение вместо execute(), использовать executeAsString() с самостоятельным парсингом ответа

**Comment by aotd1** [comment]
Попробуйте v1.0.7 и
```
vk.groups().getMembersWithFields(actor, Fields.SEX)...
```
