### ISSUE TITLE
Duplicate @SerializedName("mp_240") in com.vk.api.sdk.objects.video.VideoFiles

### ISSUE THREAD

**Issue by imayka** [VKCOM/vk-java-sdk#19]
> org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: class com.vk.api.sdk.objects.video.VideoFiles declares multiple JSON fields named mp_240

**Comment by tsivarev** [comment]
Fixed in 0.3.5 version
