### ISSUE TITLE
Выключение логгера спамера

### ISSUE THREAD

**Issue by iBuseWinner** [VKCOM/vk-java-sdk#193]
Итак, пытаюсь сделать бота, но в консоль идёт постоянный спам от sdk. Как выключить этот логгер? Помогите, пожалуйста.

Поиск в гугле ничего дельного не даёт. В коде sdk нашёл только это: https://github.com/VKCOM/vk-java-sdk/blob/master/sdk/src/main/java/com/vk/api/sdk/httpclient/HttpTransportClient.java#L202

![image](https://user-images.githubusercontent.com/44753872/77253347-93c95580-6c6a-11ea-9bc6-8bb7bca13614.png)

**Comment by maybetm** [comment]
Предлагаю сделать свою реализацию интерфейса com.vk.api.sdk.client.TransportClient с нужным логированием

**Comment by iBuseWinner** [comment]
Нашёл в тот же день, потом забыл сюда отписать. Спасибо за быстрые ответы.

Решение проблемы:
Configurator.setLevel("com.vk.api.sdk.httpclient.HttpTransportClient", Level.OFF);
