### ISSUE TITLE
в GroupsFilter отсутствует "managers"

### ISSUE THREAD

**Issue by XjCyan1de** [VKCOM/vk-java-sdk#197]
![image](https://user-images.githubusercontent.com/18630111/79458680-d0cf0080-7ffa-11ea-913a-c9061a85000b.png)
![image](https://user-images.githubusercontent.com/18630111/79458696-d7f60e80-7ffa-11ea-9843-194ad273f2fd.png)

**Comment by aotd1** [comment]
See #197, planned in 1.0.8

**Comment by aotd1** [comment]
Thanks, fixed in 1.0.8
