### ISSUE TITLE
VK Streaming API - Pong wait timeout (Duplicate #139)

### ISSUE THREAD

**Issue by Arxemond777** [VKCOM/vk-java-sdk#199]
У вас уже была такая бага [https://github.com/VKCOM/vk-java-sdk/issues/139](https://github.com/VKCOM/vk-java-sdk/issues/139) и Вы сказали, что пофиксили. Но не в версии 1.0.6 не в 1.0.3 она не пропала, у Вас есть коммит, но он в мастере этого репы https://github.com/VKCOM/vk-java-sdk/commit/0846b28327129a0436154f9ad8148a03b40c3ec7 но тега на него нет.:(
Можете по возможности создать тег?
Последний тег по доке 1.0.6 и там нет фикса этого бага [1.0.6 WSPingListener.java](https://github.com/VKCOM/vk-java-sdk/blob/version/1.0.6/sdk/src/main/java/com/vk/api/sdk/streaming/clients/websocket/WSPingListener.java#L11) фикс есть только в мастере [master WSPingListener.java]( https://github.com/VKCOM/vk-java-sdk/blob/master/sdk/src/main/java/com/vk/api/sdk/streaming/clients/websocket/WSPingListener.java#L29) как я выше написал:(

**Comment by aotd1** [comment]
В версии v1.0.8 вернули обратно, должно было починиться.
