### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by Samehadar** [VKCOM/vk-java-sdk#2]
Can you help me fix that?
>No such property: ossrhUsername for class: org.gradle.api.publication.maven.in
ternal.ant.DefaultGroovyMavenDeployer

**Comment by pepyakin** [comment]
What gradle version do you use?

**Comment by Samehadar** [comment]
I use gradle wrapper task configuration

**Comment by tsivarev** [comment]
Hi! I fixed this bug in new version (0.2.0). Now these parameters are only required for release build.

**Comment by Samehadar** [comment]
It's work, thx)

**Comment by tsivarev** [comment]
Close issue
