### ISSUE TITLE
Ошибка при получение сообщений через Bot Long Poll API

### ISSUE THREAD

**Issue by vbir94** [VKCOM/vk-java-sdk#208]
При запросе новых сообщений сообщества, используя JAVA SDK, метод
`vk.longPoll().getEvents(server, key, ts).waitTime(WAIT_TIME_SECONDS).execute()`
c ts = 2965, я получаю ошибку
`com.vk.api.sdk.exceptions.LongPollServerTsException: Incorrect 'ts' value (1): 'ts' value is incorrect, minimal value is 1, maximal value is 2971`

**Comment by DanzillaMaster** [comment]
Как получилось решить? Возникла такая же проблема...
