### ISSUE TITLE
Не доступен практически ни один метод из раздела appWidgets

### ISSUE THREAD

**Issue by wtlgo** [VKCOM/vk-java-sdk#211]
Добрый день, собственно, вся проблема описана в названии.
Если сравнить то, что есть в [документации](https://vk.com/dev/appWidgets), и список методов класса `AppWidgets`:
![image](https://user-images.githubusercontent.com/50925676/98786616-660a6a00-240f-11eb-9687-b117ed327dc8.png)
то можно обратить внимание, что имеются некоторые различия. Возможно, используется _слишком_ устаревшая версия API?

Версия `com.vk.api:sdk:1.0.6`, установлено через Maven.
Спасибо.

**Comment by aotd1** [comment]
Обновили публичную схему и Java SDK, попробуйте com.vk.api:sdk:1.0.7, там методов больше чем 0 ;)
