### ISSUE TITLE
добавление в enum KeyboardButtonActionType значения

### ISSUE THREAD

**Issue by AlexOpitev** [VKCOM/vk-java-sdk#212]
Пожалуйста добавьте в enum KeyboardButtonActionType значение:

    @SerializedName("open_link")
    OPEN_LINK("open_link");

**Comment by slava110** [comment]
Это часть PullRequest #210 . Надеюсь, его примут. Хотя тут в целом библиотеку надо обновлять, нет многих функций. @Mobyman, какие-то обновления библиотеки планируются вообще? Или лучше форкать и дорабатывать самому?

**Comment by Mobyman** [comment]
Да, конечно планируются.

**Comment by slava110** [comment]
Хорошо, будем ждать. Просто давно уже не видно активности на GitHub ¯\_(ツ)_/¯

**Comment by aotd1** [comment]
Backported and fixed in v1.0.7
