### ISSUE TITLE
1.0.8 версия SDK НЕ поддерживает VK API version 5.126.

### ISSUE THREAD

**Issue by alekseybeliyb** [VKCOM/vk-java-sdk#215]
126 версия API на событие "Входящее сообщение" отправляет следующий json:
```
{
    "type": "message_new",
    "object": {
        "message": {
            "date": 1609201902,
            "from_id": 1,
            "id": 5944,
            "out": 0,
            "peer_id": 1,
            "text": "Сообщение",
            "conversation_message_id": 5578,
            "fwd_messages": [],
            "important": false,
            "random_id": 0,
            "attachments": [],
            "is_hidden": false
        },
        "client_info": {
            "button_actions": [
                "text",
                "vkpay",
                "open_app",
                "location",
                "open_link",
                "intent_subscribe",
                "intent_unsubscribe"
            ],
            "keyboard": true,
            "inline_keyboard": true,
            "carousel": false,
            "lang_id": 0
        }
    },
    "group_id": 11,
    "event_id": "1",
    "secret": "11"
}
`````
а CallbackApi на событие "message_new" [отдаёт](https://github.com/VKCOM/vk-java-sdk/blob/9cb301b55373ea4f2c2d98bedc6761d231f8001a/sdk/src/main/java/com/vk/api/sdk/callback/CallbackApi.java#L74) объект [Message](https://github.com/VKCOM/vk-java-sdk/blob/9cb301b55373ea4f2c2d98bedc6761d231f8001a/sdk/src/main/java/com/vk/api/sdk/objects/messages/Message.java#L15), в котором нет объектов  "message" или "client_info".
[Изменения](https://vk.com/dev/versions) в "message_new" произошли в версии 5.103.
![image](https://user-images.githubusercontent.com/47724828/103251217-49130180-4991-11eb-8f98-e27d052641b5.png)

Таким образом, последняя поддерживаемая версия API - 5.102

**Comment by aotd1** [comment]
Fixed in 1.0.9, please check
