### ISSUE TITLE
Ошибка парсинга поста с с геотегом

### ISSUE THREAD

**Issue by sieur** [VKCOM/vk-java-sdk#22]
При получении поста, в котором есть геотег ко всему посту происходит ошибка парсинга.
Парсер ожидает, что поле country - число, вместо этого в поле строка.

Пост: https://vk.com/mamin_peterburg?w=wall-79272609_15336
JSON:
![fb07ee62bfc857ce630828ee2308ed45](https://cloud.githubusercontent.com/assets/4561606/20504496/d156a0c8-b058-11e6-9c7b-9d733ac03e02.png)

ошибка при вызове **gson.fromJson(response, responseClass)** в классе **abstract class ApiRequest<T>**

`        try {
            return gson.fromJson(response, responseClass);
        } catch (JsonSyntaxException e) {
            LOG.error("Invalid JSON: " + textResponse, e);
            throw new ClientException("Can't parse json response");
        }`

Caused by: java.lang.NumberFormatException: For input string: "Россия"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_31]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_31]

**Comment by tsivarev** [comment]
Fixed in 0.3.6 version
