### ISSUE TITLE
Текст сообщения с LongPoll event-а всегда равен null

### ISSUE THREAD

**Issue by 2sweetheart2** [VKCOM/vk-java-sdk#236]
Столкнулся с проблемой, что при LongPoll event-е, текст сообщения всегда равен null, но остальные евенты работают корректно. Сам класс слушателя взял из примера [слушателя](https://github.com/VKCOM/vk-java-sdk/blob/master/examples/callback-api-group-bot/src/main/java/com/vk/api/examples/group/bot/CallbackApiLongPollHandler.java). В чем может быть проблема?

**Comment by 2sweetheart2** [comment]
в дальнейшем узналось, что при парсинге json строки в объект Message происходит что-то странное, и в итоге весь объект Message пустой, в плане все переменные в нём равны null
![image](https://user-images.githubusercontent.com/69629490/132746342-1a228d8c-8c28-45d9-b03c-4ae6d4a63092.png)

**Comment by 2sweetheart2** [comment]
![image](https://user-images.githubusercontent.com/69629490/132748581-02a9d7b8-aeb8-4506-ac87-8c0c8e54df7e.png)

**Comment by mkfl3x** [comment]
Это происходит из-за неправильной структуры возвращаемого объекта сообщения (скорее всего).
[Тут](https://github.com/mkfl3x/vk-bot/blob/main/src/main/java/com/vkbot/callback/CallbackController.java) можно посмотреть как это победить

**Comment by 2sweetheart2** [comment]
> Это происходит из-за неправильной структуры возвращаемого объекта сообщения.
> [Тут](https://github.com/mkfl3x/vk-bot/blob/main/src/main/java/com/vkbot/callback/CallbackController.java) можно посмотреть как это победить.
> [Этот пример](https://github.com/VKCOM/vk-java-sdk/blob/master/examples/callback-api-group-bot/src/main/java/com/vk/api/examples/group/bot/CallbackApiLongPollHandler.java) работать не будет, увы. Поэтому десериализацию надо костылить как я писал выше.

тебя понял, спасибо за наводку;)
