### ISSUE TITLE
DoS эксплоит в библиотеке log4j

### ISSUE THREAD

**Issue by wtlgo** [VKCOM/vk-java-sdk#250]
Кажется, это становится еженедельной традицией: еще один критический эксплоит в log4j, еще один патч 2.17.0

https://logging.apache.org/log4j/2.x/security.html (или ссылка, [привязанная к сегодня](https://web.archive.org/web/20211218110236/https://logging.apache.org/log4j/2.x/security.html))

**Comment by aotd1** [comment]
Ага, слежу за ними, в v1.0.14 бампнуто
