### ISSUE TITLE
Генерация random_id для отправки сообщений

### ISSUE THREAD

**Issue by LymonMine** [VKCOM/vk-java-sdk#257]
Как сгенерировать random_id для отправки сообщений?

**Comment by mkfl3x** [comment]
`new Random().nextInt()`

**Comment by LymonMine** [comment]
> `new Random().nextInt()`
![2022-01-17_21-21-31](https://user-images.githubusercontent.com/93972633/149806175-2d2dabb8-75b1-46a8-b27b-54ecfb480c89.png)
Сообщения приходят, но возникает ошибка(показано на скриншоте)

**Comment by LymonMine** [comment]
И кое что по отправке сообщения. Если чата с сообществом и пользователем не было, то пишет что нет прав для отправки сообщения. Как сделать что бы если чата с сообществом и пользователем не было, то сообщения отправлялись

**Comment by mkfl3x** [comment]
Ошибка возникает потому что модель (java класс), в который десериализуется ответ, не соответствует получаемому json объекту. Это проблема самого SDK.

**Comment by mkfl3x** [comment]
Если нет прав, то значит либо пользователь ограничил возможность писать ему сообществом, либо у сообщества нет прав не отправку сообщений (нужно проверить scope прав, который был использован для генерации токена)

**Comment by LymonMine** [comment]
> Если нет прав, то значит либо пользователь ограничил возможность писать ему сообществом, либо у сообщества нет прав не отправку сообщений (нужно проверить scope прав, который был использован для генерации токена)

Там есть все права, но пока пользователь с сообществом диалог не заведёт api не сможет отправить сообщение

**Comment by LymonMine** [comment]
> Ошибка возникает потому что модель (java класс), в который десериализуется ответ, не соответствует получаемому json объекту. Это проблема самого SDK.

И как это исправить?

**Comment by mkfl3x** [comment]
Обрабатывать объект не передавая в метод `parse()`, используя свою модель, например
