### ISSUE TITLE
MessagesGetLongPollHistoryQuery sends request to wrong URL

### ISSUE THREAD

**Issue by kokorin** [VKCOM/vk-java-sdk#29]
A request is sent to `messages.getLongPollHistory`, but it should be sent to `https://{$server}?act=a_check&key={$key}&ts={$ts}&wait=25&mode=2&version=1` as stated [here](https://vk.com/dev/using_longpoll)

**Comment by tsivarev** [comment]
@kokorin Why? This query for https://vk.com/dev/messages.getLongPollHistory

**Comment by kokorin** [comment]
There are several problems with https://vk.com/dev/messages.getLongPollHistory:
1. It doesn't allow long polling actually. 
2. [here](https://vk.com/dev/using_longpoll) it is stated, that request to `getLongPollServer` is required. In the response there are both `server` and `key` parameters. Current implementation of `MessagesGetLongPollHistoryQuery`  has no such parameters.
