### ISSUE TITLE
MessagesSendQuery#attachment doesn't mention access_key

### ISSUE THREAD

**Issue by pepyakin** [VKCOM/vk-java-sdk#3]
Documentation of 
[MessagesSendQuery#attachment](https://github.com/VKCOM/vk-java-sdk/blob/master/sdk/src/main/java/com/vk/api/sdk/queries/messages/MessagesSendQuery.java#L133
) doesn't mention that [access_key](https://vk.com/dev/access_key) should be included for sending attachments that links to the private media.
I think that information should be reflected in documentation, because VK API will just ignore `attachment` parameter, if it has no `access_key`.
If one will try to send message with only private attachment (i.e. without message body) without `access_key` then server will respond that there is no `message` parameter (which is optional if `attachment` present), which is very confusing.

**Comment by tsivarev** [comment]
Yes, you are right. I will add information about `access_key` in next minor release.
