### ISSUE TITLE
Option to disable logger

### ISSUE THREAD

**Issue by djarktic** [VKCOM/vk-java-sdk#37]
I'am not using log4j, and I dont want to use it.
So I always get error in stdout:
`SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.webjars.WebJarExtractor
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`
Maybe we should to add option to disable sdk logging?

**Comment by tsivarev** [comment]
I changed logger from Log4j2 to SLF4J. If you want to turn on logging, you must include a plugin that bridges SLF4J with a concrete logging framework. See [SLF4J documentation](http://www.slf4j.org/manual.html#swapping).
