### ISSUE TITLE
Error when i try getting posts from id=1

### ISSUE THREAD

**Issue by 7Dump** [VKCOM/vk-java-sdk#4]
GetResponse getResponse = vk.wall().get().ownerId(1).count(100).execute();

I get:

> com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216) ~[gson-2.6.2.jar:?]
>   at com.google.gson.Gson.fromJson(Gson.java:879) ~[gson-2.6.2.jar:?]
>   at com.google.gson.Gson.fromJson(Gson.java:944) ~[gson-2.6.2.jar:?]
>   at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:85) [sdk-0.2.0.jar:?]

Full JSON here: https://gist.github.com/7Dump/e22da453b6dbae18c274bf62336e19ce

**Comment by 7Dump** [comment]
https://github.com/VKCOM/vk-java-sdk/blob/cd26883131f0ace29fe815920122cfc4a997c967/sdk/src/main/java/com/vk/api/sdk/objects/base/Place.java#L63

Country as Integer but in JSON response "country": "Russia"

**Comment by djarktic** [comment]
same bug with messages.getHistory
