### ISSUE TITLE
Missing fields related to Groups

### ISSUE THREAD

**Issue by Rocknest** [VKCOM/vk-java-sdk#51]
Group: "has_photo", "invited_by";
GroupFull: "is_hidden_from_feed", "can_upload_doc", "place", "public_date_label", "ban_info".

Field "deactivated" should be in Group.

Also missing option "COVER" in GroupField enum.

Field "id" in Group is String instead of Integer.

**Comment by tsivarev** [comment]
"invited_by" returns in groups.getInvites method only. So, see GroupXtrInvitedBy.
