### ISSUE TITLE
CallBack API

### ISSUE THREAD

**Issue by nuancat** [VKCOM/vk-java-sdk#54]
Добрый день. Интересуюсь нововведением в ВК, конкретно CallBack API.
Не понимаю один момент в документации

`
public class CallbackApiHandler extends CallbackApi { 
  @Override 
  public void messageNew(Integer groupId, Message message) { 
    System.out.println(message.getBody()); 
  } 
} 

... 
CallbackApiHandler callbackApiHandler = new CallbackApiHandler(); 

String body = httpRequest.getBody(); 
callbackApiHandler.parse(body);
`

Откуда появился httpRequest? Нужно делать реализовывать свой http сервер?

**Comment by tsivarev** [comment]
Да, нужно использовать http-сервер, т.к. callback API это отправка запросов со стороны ВК на ваш сервер.
