### ISSUE TITLE
No method groupAuthorizationCodeFlow under OAuth method

### ISSUE THREAD

**Issue by Kanaris** [VKCOM/vk-java-sdk#6]
This example doesn't work

AuthGroupResponse authResponse = vk.oauth()
    .groupAuthorizationCodeFlow(APP_ID, CLIENT_SECRET, REDIRECT_URI, code, groupId)
    .execute();

GroupActor actor = new GroupActor(authResponse.get(), authResponse.getAccessToken());

**Comment by tsivarev** [comment]
I fixed it in 0.3.0 version.

New example:
`AuthResponse authResponse = vk.oauth().authorizationCodeFlow(clientId, clientSecret, redirectUri, code).execute();
GroupActor actor = new GroupActor(groupId, authResponse.getAccessToken());`

**Comment by tsivarev** [comment]
New example after 0.3.1 version:

`GroupAuthResponse authResponse = vk.oauth().groupAuthorizationCodeFlow(clientId, clientSecret, redirectUri, code).execute();
GroupActor actor = new GroupActor(groupId, authResponse.getAccessTokens().get(groupId));`
