### ISSUE TITLE
(Стикеры) Некорректно работает метод apiClient.messages.send(actor).stickerId(stickerId).execute();

### ISSUE THREAD

**Issue by suuchbaka** [VKCOM/vk-java-sdk#61]
В ответ присылает "..."

_Извините если неправильно составил тикет, делаю это впервые, спасибо!_

**Comment by tsivarev** [comment]
Такое может быть из-за того, что данный стикер недоступен для отправки. Если вы отправляете с токеном пользователя, то проверьте, что набор стикеров куплен/доступен. А если с токеном группы, то сейчас эта функциональность еще не доступна.
