### ISSUE TITLE
Bring back the upload component of the Audio API

### ISSUE THREAD

**Issue by driver733** [VKCOM/vk-java-sdk#66]
According to the [official VK dev portal](https://vk.com/dev/audio_api) the methods that deal with uploading audio files are still working.

> Existing methods for the audio section will be unavailable for calling, **except for methods regarding audio file uploads.**

Therefore, I suggest to bring the audio upload component back.
Here are the commits that removed the audio upload functionality.
f12e5cbc7d913b2459f5a8a648bdff4866b0c9c4
9917ad8c4a8aee8019060da9aa42f392c174376a

**Comment by tsivarev** [comment]
Sorry, Audio API is fully depreciated.
