### ISSUE TITLE
Something wrong with README.md

### ISSUE THREAD

**Issue by BenderRodrigez** [VKCOM/vk-java-sdk#71]
As you can see on attached screenshot, LATEST_VERSION contains wrong symbol in Maven dependency and also it is not automatically replaced with proper version (which I guess should be replaced here)
<img width="556" alt="2017-07-04 17 03 25" src="https://user-images.githubusercontent.com/4478255/27831305-2718466e-60db-11e7-9092-e5a63aa134ca.png">

**Comment by tsivarev** [comment]
It's not bug. You need to change 'LATEST_VERSIONS' variable yourself.
