### ISSUE TITLE
Access denied (15): Access denied: user deactivated

### ISSUE THREAD

**Issue by AntonYurchenko** [VKCOM/vk-java-sdk#74]
Добрый день,
Делаю запрос друзей пользователя (всех друзей с использованием ```ServiceActor```), у которого в друзьях есть заблокированные аккаунты
```scala
val setIds = vk.friends().get(actor).userId(userId).execute().getItems.asScala.map(_.toInt).toSet
```
 в итоге получаю исключение
```bash
Exception in thread "main" com.vk.api.sdk.exceptions.ApiAccessException: Access denied (15): Access denied: user deactivated
```
Соответственно весь запрос падает. Вопрос, как получить id всех друзей в таком случае?

Спасибо

**Comment by bobrovnikov** [comment]
@AntonYurchenko,
Для эксперимента добавил к себе в друзья заблоченный аккаунт: https://vk.com/id430901776

```
List<Integer> setIds = vk
                    .friends()
                    .get(actor)
                    .userId(3011229)
                    .execute()
                    .getItems();

System.out.print(setIds);
```

Вывод выглядит примерно так: `[..., ..., 430901776]`, т.е. id заблокированного пользователя всё-таки присутствует в выдаче, а сам запрос не выдаёт исключения.

Какие ещё возможные шаги следует предпринять для воспроизведения описанной проблемы?

**Comment by AntonYurchenko** [comment]
@bobrovnikov 
Прошу прощения, нашел ошибку у себя в коде.
Спасибо.
