### ISSUE TITLE
market.edit: Impossible to set price = 90 000 000

### ISSUE THREAD

**Issue by haruda** [VKCOM/vk-java-sdk#83]
It is impossible to set price=90000000 with Java SDK but it is working OK with direct API request.

Successful request example: 
https://api.vk.com/method/market.edit?user_id=1789332&v=5.67&access_token=11b93be95652b545123080fa60cf6fc7930c8c4c1f4ea72163fc6e4e293b6f4e6800f72612f8e1d2f661a&owner_id=-151902276&name=_123456789_A&description=AAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaa&category_id=5&price=90000000&main_photo_id=456239341&item_id=923324&cc_key=

Example of SDK request:
vk.market().edit(
new UserActor(1789332,
"11b93be95652b545123080fa60cf6fc7930c8c4c1f4ea72163fc6e4e293b6f4e6800f72612f8e1d2f661a"),
-151902276, 923324, "TEST name", "DESCRIPTION__", 5,
90000000,
456239341)
.execute();

**Comment by tsivarev** [comment]
Fixed
