### ISSUE TITLE
Вызов метода "users.get" с GroupActor

### ISSUE THREAD

**Issue by sboychenko** [VKCOM/vk-java-sdk#89]
В документации описано, что метод можно вызывать с ключем доступа сообщества:
https://vk.com/dev/users.get

В sdk (v 0.5.9) 
```
GroupActor actor = new GroupActor(groupId, token);
vk.users().get(actor).userIds(userId).fields(UserField.BDATE, UserField.CONTACTS).execute();
```
Метод `get()` есть только для ServiceActor и UserActor

**Comment by tsivarev** [comment]
Fixed
