### ISSUE TITLE
Actor id, wall

### ISSUE THREAD

**Issue by XakepSDK** [VKCOM/vk-java-sdk#9]
Если использовать GroupActor и постить через client.wall(), то постится на стену аккаунта, а не группы.
Быстро пройдя по дереву вызовов обнаружил, что в конструкторе `WallPostQuery` не хватает
`ownerId(actor.getId());`

**Comment by tsivarev** [comment]
Метод wall.post на данный момент не доступен для вызова с токеном группы.

> Этот метод можно вызвать с ключом доступа пользователя, полученным в Standalone-приложении через Implicit Flow, или с использованием окна подтверждения. Требуются права доступа: wall.

https://vk.com/dev/wall.post

**Comment by XakepSDK** [comment]
Вот только авторизуюсь я через пользователя и всё работает, если указать вместо своего id id группы.

**Comment by tsivarev** [comment]
@XakepSDK а можно пример кода?

**Comment by XakepSDK** [comment]
```
Actor actor1 = new GroupActor(GROUP_ID, ACCESS_TOKEN);
vk.wall().post(actor1).message("test").fromGroup(true).signed(false).ownerId(-GROUP_ID).execute();
```
И еще в нескольких местах смотрел, используется ли id из actor'а - не используется. Зачем он там вообще тогда? Зачем несколько actor'ов, если там разницы никакой нет?

**Comment by tsivarev** [comment]
ACCESS_TOKEN - а это токен пользователя?

**Comment by XakepSDK** [comment]
Да.

**Comment by tsivarev** [comment]
GroupActor - это класс, который хранит информацию об авторизации группы, а UserActor, соответственно, о пользователе. В GroupActor нужно передавать токен [сообщества](https://vk.com/dev/access_token?f=2.%20%D0%9A%D0%BB%D1%8E%D1%87%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B0).

**Comment by XakepSDK** [comment]
1. В них никакой разницы нет, разве что еще 1 метод в GroupActor'е и минус в начале добавляет
2. ID нигде не используется(по крайней мере, где я смотрел).
Не легче ли тогда сразу токен передавать и миновать лишний класс?

**Comment by tsivarev** [comment]
В новой версии SDK (0.3.2), action-методы принимают конкретный actor в зависимости от того, кто может вызвать метод:
`
//Можно вызвать только с токеном пользователя
public MarketGetQuery get(UserActor actor, int ownerId) {..}
...
//Можно вызвать только с сервисным токеном
public SecureGetAppBalanceQuery getAppBalance(ServiceActor actor) {...}
...
//Можно вызвать с токеном группы и пользователя
public GroupsGetCallbackSettingsQuery getCallbackSettings(Actor actor, int groupId) {...}
`

**Comment by XakepSDK** [comment]
Понятно.
Как правильно файл загрузить? см. 
https://github.com/VKCOM/vk-java-sdk/issues/9#issuecomment-254445853

**Comment by tsivarev** [comment]
Пример:

```
Photo uploadWallPhoto(Path image) {
    PhotoUpload serverResponse =VK.photos().getWallUploadServer(actor).execute();
    WallUploadResponse uploadResponse =VK.upload().photoWall(serverResponse.getUploadUrl(), image.toFile()).execute();

    List<Photo> photoList  = VK.photos().saveWallPhoto(actor, uploadResponse.getPhoto()) .server(uploadResponse.getServer()).hash(uploadResponse.getHash()).execute();

    return photoList.get(0);
}
```

**Comment by XakepSDK** [comment]
`15:19:18.650 [main] ERROR com.vk.api.sdk.client.ApiRequest - API error
com.vk.api.sdk.exceptions.ApiParamException: One of the parameters specified was missing or invalid (100): One of the parameters specified was missing or invalid: photos_list is invalid`
photos_list пустой, загружаю картинку без расширения.(png или jpeg)

**Comment by tsivarev** [comment]
Есть тест для воспроизведения?

**Comment by XakepSDK** [comment]
```
String uploadServer = vk.photos().getWallUploadServer(actor).groupId(-GROUP_ID).execute().getUploadUrl();

File img = new File("img");
FileUtils.copyURLToFile(new URL(url), img);

WallUploadResponse wur = vk.upload().photoWall(uploadServer, img).execute();
```

**Comment by tsivarev** [comment]
А почему отрицательный GROUP_ID в
`vk.photos().getWallUploadServer(actor).groupId(-GROUP_ID).execute().getUploadUrl();`? 
Лучше пример через pull request вместе с картинкой, что бы я смог запустить.

**Comment by XakepSDK** [comment]
```
        final int ID = 130467966;
        final String TOKEN = "abcdefg";
        Actor actor = new GroupActor(ID, TOKEN);
        File img = new File("img");
        String uploadServer = vk.photos().getWallUploadServer(actor).groupId(-ID).execute().getUploadUrl();
        WallUploadResponse wur = vk.upload().photoWall(uploadServer, img).execute();
```
Еще попробовал с форматом изображения. Выдает ошибку 121(invalid hash), но описание ошибки на странице с ошибками нет.

**Comment by tsivarev** [comment]
Параметр groupId должен быть положительным.

```
final int ID = 130467966;
        final String TOKEN = "abcdefg";
        Actor actor = new GroupActor(ID, TOKEN);
        File img = new File("img");
        String uploadServer = vk.photos().getWallUploadServer(actor).groupId(ID).execute().getUploadUrl();
        WallUploadResponse wur = vk.upload().photoWall(uploadServer, img).execute();
```

**Comment by XakepSDK** [comment]
К сожалению, та же ошибка.
